import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UseLayoutProvider } from "@/context/LayoutContext";
import { UseCreateTaskProvider } from "@/context/CreateTaskContext";
import { UseLogInProvider } from "@/context/LoginContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Steward IQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UseLayoutProvider>
        <UseCreateTaskProvider>
          <UseLogInProvider>
          <body className={inter.className}>{children}</body>
          </UseLogInProvider>
        </UseCreateTaskProvider>
      </UseLayoutProvider>
    </html>
  );
}
